export const contractAddress = ""

export const NFTStorageToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDExNzY3RkFENGM1YzM3NDBiYTkwNzZiMjBFYzNhNzc4Njg0OTVkRjciLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY1OTg1NjI2NzIyMCwibmFtZSI6ImhidSJ9.ACEzGTBusY378h9qf01FaVKArQo86sh-uoOlg1pi3ao"